variables:
  VERSION: "$CI_PIPELINE_ID"
  ASPNETCORE_ENVIRONMENT: "Production"

stages:
  - build
  - test
  - deploy

before_script:
  - eval "$(ssh-agent -s)"
  - cat ~/.ssh/id_rsa | ssh-add - > /dev/null
  - ssh-keyscan github.com >> ~/.ssh/known_hosts
  - echo $GITHUB_URL

build-test-service:
  stage: build
  script:
    - docker-compose build
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker-compose push

test-test-business:
  stage: test
  needs: [build-test-service]
  script:
    - docker build -t test-business:latest -f TM.TestService.UnitTests/Dockerfile .
    - docker run --rm -t test-business:latest dotnet test --logger:"console;verbosity=normal"
    - docker image rm test-business:latest
        
deploy-test-service:
  stage: deploy
  # needs: [test-test-business]
  script:
    - ssh git@github.com || true
    - git remote remove origin && git remote add origin $GITHUB_URL
    - git config --global --add safe.directory $(pwd)
    - git fetch --unshallow $GITHUB_URL
    - git push origin HEAD:master -f
    - git config --global --unset safe.directory $(pwd) || true
    - rm -rf *
    - git clone $GITOPS_URL 
    - cd GitOps
    - git config --global --add safe.directory $(pwd)
    - git branch origin/tm/test-service
    - sed -i 's/tm.test-service:[0-9]*/tm.test-service:$VERSION/g' ./setup/deployment.yaml
    - git add ./setup/deployment.yaml
    - git commit -m "change to version $VERSION"
    - git push origin tm/test-service
    - git config --global --unset safe.directory $(pwd) || true