variables:
  VERSION: "$CI_PIPELINE_ID"
  ASPNETCORE_ENVIRONMENT: "Production"

stages:
  - build
  - test
  - deploy

before_script:
  - eval "$(ssh-agent -s)"
  - cat ~/.ssh/id_rsa | ssh-add - > /dev/null
  - ssh-keyscan github.com >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - ssh git@github.com
  - git remote rm origin
  - git remote add origin git@github.com:kinhnv/TM.TestService.git

build-test-service:
  stage: build
  script:
    - docker-compose build
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker-compose push

test-test-business:
  stage: test
  needs: [build-test-service]
  script:
    - docker build -t test-business:latest -f TM.TestService.UnitTests/Dockerfile .
    - docker run --rm -t test-business:latest dotnet test --logger:"console;verbosity=normal"
    - docker image rm test-business:latest
        
deploy-test-service:
  stage: deploy
  needs: [test-test-business]
  script:
    - git config --global --add safe.directory $(pwd)
    - git push origin origin/master
    - git config --global --unset safe.directory $(pwd)