variables:
    VERSION: "$CI_PIPELINE_ID"
    ASPNETCORE_ENVIRONMENT: "Production"

stages:
    - build
    - test
    - deploy

before_script:
    - apt-get update -y && apt-get install -yqqf openssh-client git unzip sshpass rsync --fix-missing
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_TOOLKIT" | tr -d '\r' | ssh-add - > /dev/null

    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    - ssh-keyscan $GITHUB_URL >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

    - git config --global user.email "our@email.com"
    - git config --global user.name "Gitlab Runner"

build-test-service:
    stage: build
    script:
        - docker-compose build
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - docker-compose push

test-test-business:
    stage: test
    needs: [build-test-service]
    script:
        - docker build -t test-business:latest -f TM.TestService.UnitTests/Dockerfile .
        - docker run --rm -t test-business:latest dotnet test --logger:"console;verbosity=normal"
        - docker image rm test-business:latest
        
deploy-test-service:
    stage: deploy
    needs: [test-test-business]
    script:
        - git config --global --add safe.directory $(pwd)
        - echo $ROOT_PASSWORD | sudo -S git remote add github $GITHUB_URL
        - git push origin origin/master
        - echo $ROOT_PASSWORD | sudo -S git remote remove github
        - git config --global --unset safe.directory $(pwd)