variables:
  VERSION: "$CI_PIPELINE_ID"
  ASPNETCORE_ENVIRONMENT: "Production"

stages:
  - build
  - update_github
  - test
  - update_gitops

before_script:
  - eval "$(ssh-agent -s)"
  - cat ~/.ssh/id_rsa | ssh-add - > /dev/null
  - ssh-keyscan github.com >> ~/.ssh/known_hosts
  - echo $GITHUB_URL

build:
  stage: build
  only:
    - master
  script:
    - docker-compose build
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker-compose push

update-github:
  stage: update_github
  only:
    - master
  script:
    - ssh git@github.com || true
    - git remote remove origin && git remote add origin $GITHUB_URL
    - git config --global --add safe.directory $(pwd)
    - git fetch --unshallow $GITHUB_URL
    - git push origin HEAD:master -f
    - git config --global --unset safe.directory $(pwd) || true

test:
  stage: test
  only:
    - master
  needs: [build]
  script:
    - docker build -t test-business:latest -f TM.TestService.UnitTests/Dockerfile .
    - docker run --rm -t test-business:latest dotnet test --logger:"console;verbosity=normal"
    - docker image rm test-business:latest
        
update-gitops:
  stage: update_gitops
  only:
    - master
  needs: [test]
  script:
    - git clone $GITOPS_URL 
    - cd GitOps
    - git config --global --add safe.directory $(pwd)
    - git checkout -b tm/test-service origin/tm/test-service
    - sed -i "s/tm.test-service:[0-9]*/tm.test-service:$VERSION/g" ./setup/deployment.yml
    - git add ./setup/deployment.yml
    - git config --global user.email "kinhnv1801@gmail.com"
    - git config --global user.name "Nguyen Van Kinh"
    - git commit -m "change to version $VERSION"
    - git push origin tm/test-service
    - git config --global --unset safe.directory $(pwd) || true