version: '3.7'
services:
  test-admin:
    image: kinhnv1801/tm.test-service:${VERSION}
    build:
      context: .
      dockerfile: ./TM.TestService.Api/Dockerfile
    ports:
      - "40000:80" 
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    networks:
      - tm-network
  ngrok:
    image: ngrok/ngrok:alpine
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
      - NGROK_CONFIG=/etc/ngrok.yml
    networks:
      - tm-network
networks:
  tm-network:
